export {
  cancelReservation,
  createReservation,
  getActiveReservation,
  getMachineHistory,
  getReservationAvailability,
  getReservationHistory,
  getRoomActiveReservations,
  type HistoryQuery,
  type ReservationHistoryQuery,
} from "./api/reservationApi"
export {
  normalizeCancellationResult,
  normalizeMachineHistoryPage,
  normalizeReservation,
  normalizeReservationAvailability,
  normalizeReservationHistoryPage,
  normalizeRoomActiveReservationsResponse,
  RESERVATION_STATUSES,
  RESERVED_TIMEOUT_MINUTES,
  type CancellationResult,
  type MachineHistoryItem,
  type Page,
  type Reservation,
  type ReservationAvailability,
  type ReservationHistoryItem,
  type ReservationMachineType,
  type ReservationStatus,
} from "./model/reservation"
