name: Washer-Client CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Lint
        run: pnpm run lint
        continue-on-error: true
        
      - name: Type check
        run: pnpm exec tsc --noEmit
        continue-on-error: true
        
      - name: Copy .env file
        run: cp /root/.env .env
        
      - name: Build app
        run: pnpm run build
        
      - name: Install PM2 globally
        run: |
          npm install -g pm2
          
      - name: Restart app with PM2
        run: |
          echo "=== 기존 프로세스 정리 ==="
          pm2 stop washer-client || true
          pm2 delete washer-client || true
          
          echo "=== Next.js 직접 실행 ==="
          # ecosystem.config.js 대신 직접 명령어로 실행
          pm2 start npm --name "washer-client" -- start
          
          echo "=== PM2 저장 및 최종 상태 ==="
          pm2 save
          pm2 list
