name: Washer-Client CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
      continue-on-error: true

    - name: Type check
      run: npx tsc --noEmit
      continue-on-error: true

    - name: Build app
      run: npm run build

    - name: Install PM2 locally
      run: npm install pm2

    - name: Restart app with PM2
      run: |
        npx pm2 restart washer-client || npx pm2 start npm --name washer-client -- start
        npx pm2 save
