name: Deploy Static Build (Alternative)

on:
    push:
        branches: [main, master]

jobs:
    deploy-static:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build static export
              run: |
                  npm run build
                  npm run export
              env:
                  NODE_ENV: production

            - name: Deploy to nginx
              run: |
                  sudo rm -rf /var/www/html/*
                  sudo cp -r out/* /var/www/html/
                  sudo chown -R www-data:www-data /var/www/html
                  sudo chmod -R 755 /var/www/html

            - name: Reload nginx
              run: sudo systemctl reload nginx

            - name: Health check
              run: |
                  sleep 2
                  curl -f http://localhost || exit 1
